### ISSUE TITLE
Scoped reducers

### ISSUE THREAD

**Issue by asciiman** [thebakeryio/react-native-complex-nav#13]
Hello,

In your [tutorial](http://blog.thebakery.io/react-native-experimental-navigation-with-redux/) you talk about how you scope the navigation reducers.

```
export default connect(mapStateToProps, mapDispatchToProps, (stateProps, dispatchProps, ownProps) => {
  return Object.assign({}, ownProps, stateProps, dispatchProps, {
    onNavigate: (action) => {
      dispatchProps.dispatch(Object.assign(action, {
        scope: action.scope || stateProps.navigation.key
      }));
    }
  });
})(Feed);
```

I don't see any scoping in your example, though.  I am wondering how you are guaranteeing that new screens are being pushed onto the correct stack?

**Comment by callmephilip** [comment]
I moved this logic in a reusable library - https://github.com/thebakeryio/react-native-navigation-redux-helpers
The example has been migrated to use these helpers. Unfortunately, I have not had a chance to update the original article with appropriate snippets

**Comment by callmephilip** [comment]
More specifically, you can see how scoping happens on the action level here: https://github.com/thebakeryio/react-native-complex-nav/blob/master/app/components/GlobalNavigation/index.js#L67

Reducers are aware of scoping automatically

**Comment by asciiman** [comment]
Thank you.  I got it working!
