### ISSUE TITLE
Failed to run on Android with error message "Unfortunately, NativeReactApp has stopped."

### ISSUE THREAD

**Issue by joshloo** [thebakeryio/react-native-complex-nav#14]

**Comment by himanshusoni** [comment]
+1

Any updates on this issue ?

**Comment by himanshusoni** [comment]
Refer to PR #10 

You need to add the below line in your AndroidManifest.xml
`android:name=".MainApplication"`

**Comment by callmephilip** [comment]
I've just migrated this to RN 32 and included the fix. Hope this works. Feel free to reopen if it's still failing
