### ISSUE TITLE
Question: Can each tab retain it's state ?

### ISSUE THREAD

**Issue by esutton** [thebakeryio/react-native-complex-nav#2]
For example, if **tab2** was also an items tab.
1. User selects, **Hello3** in tab2
2. User selects **Settings** tab
3. User return to **tab2**, and **Hello3** is still selected

Thank you for this example.  I am having a hard time getting the UIExplorer example to run in react-native 26 so that I may evaluate NavigatorExperimental. Your example ran the first time. 

 I hope to use NavigatorExperimental on both Android and iOS and replace my existing use of NavigatorIOS.

[react-native UIExplorer will not run in iOS simulator? ( red-box “No script URL provided” )](http://stackoverflow.com/questions/37396001/react-native-uiexplorer-will-not-run-in-ios-simulator-red-box-no-script-url)

**Comment by callmephilip** [comment]
As long as you have a stack reducer for the view inside Tab2, it should be doable. It already works with Tab 1 so should be doable with any other section of the app

**Comment by esutton** [comment]
Thank you for the explanation and sharing your work
