### ISSUE TITLE
Doesn't work on RN 0.28 - undefined on nextState.routes.forEach

### ISSUE THREAD

**Issue by avishayil** [thebakeryio/react-native-complex-nav#6]
![Stack Trace](http://i.imgur.com/L7t6Bmn.png)

**Comment by jlpiedrahita** [comment]
There are some breaking changes related to navigation in RN 0.28: https://github.com/facebook/react-native/releases/tag/v0.28.0

You can either stick with 0.27 or submit a PR renaming `children` as `routes` in your navigation state.

**Comment by callmephilip** [comment]
Should be fixed now - there have been a bunch of changes in the API - https://github.com/thebakeryio/react-native-complex-nav/pull/7/files
